services:
  - type: worker
    name: queue
    region: ohio
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
  